### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by pyros-cyber** [ottyanna/traynim#9]
Hello, 

everything works until I try to run: 
`$ ./traynim renderer`
it returns the error
`ERROR: file examples/example.txt at line 23 and column 55: cannot open file stream: tests/HdrImageReferences/grass.pfm [GrammarError]`

Looking into the directory mentioned above, it seems that `grass.pfm` does not exist. 

Steps to reproduce: 
- Download latest release
- `$ tar -xvf traynim-1.0.0.tar.gz`
- `$ cd traynim-1.0.0`
- `$ nimble test` (all tests are passing)
- `$ nimble run traynim` (it compiles fine)
- `$ ./traynim renderer` 

Best regards, keep up the good work,
Simone

**Comment by ottyanna** [comment]
Fixed with PR #10

**Comment by pyros-cyber** [comment]
Hello, thanks for fixing it this fast, now it works like a charm!

Keep up the good work,
Best regards,
Simone
